### ISSUE TITLE
Publicação e manutenção

### ISSUE THREAD

**Issue by jemluz** [jemluz/ds-ignite-call#5]
## Publicando StoryBook

Vamos usar a biblioteca [Storybook Deployer](https://www.npmjs.com/package/@storybook/storybook-deployer/v/2.5.2) para otimizar nosso processo de publicação

Criado o arquivo deploy-docs.yml par configurar a pipeline/rotina de deploy do storbook
```yml
name: Deploy docs

# the pipe will be run everytime that master branch has a push
on:
  push:
    branches:
      - master

# define steps of pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # do checkout to get the code
        uses: actions/checkout@v4

      - name: Setup Node.js #  install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci # do npm install (made by ci environment, what will isnt modify the package-lock, this is important!)

      - run: npm run build # run turborepo build

      - name: Deploy storybook # do deploy
        working-directory: ./packages/docs # enter on storybook folder
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static # run deploy command
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
```

Precisei utilizar as issues [Erro ao visualizar a página publicada do storybook](https://app.rocketseat.com.br/h/forum/react-js/7bc36410-ee46-4014-adbe-fbe4e83fbdd0) e [Erro no deploy do Storybook url retorna erro 403](https://app.rocketseat.com.br/h/forum/react-js/6c429e27-fce4-43eb-b1b4-4b34b4f52a38) para deixar o deploy redondinho

Também teve a configuração do GH Pages para gerar a pipe de hospedagem
![image](https://github.com/user-attachments/assets/ac665982-6bae-4acc-b953-6955ebedf762)
